
export const quotes = [
  "Do, or do not. There is no 'try'. - Yoda, Star Wars",
  "Every man dies, but not every man really lives. - William Wallace, Braveheart",
  "Don't let anyone ever make you feel like you don't deserve what you want. - Patrick Verona, 10 Things I Hate About You",
  "Great men are not born great, they grow great. - Mario Puzo, The Godfather",
  "It's what you do right now that makes a difference. - Black Hawk Down",
  "Just because someone stumbles and loses their path, doesn't mean they're lost forever. - Professor Charles Xavier, X-Men: Days of Future Past",
  "Life is not the amount of breaths you take. It's the moments that take your breath away. - Alex Hitchens, Hitch",
  "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it. - Ferris Bueller, Ferris Bueller's Day Off",
  "Nobody is gonna hit as hard as life, but it ain't how hard you can hit. It's how hard you can get hit and keep moving forward. It's how much you can take, and keep moving forward. That's how winning is done. - Rocky Balboa, Rocky Balboa",
  "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. - Marianne Williamson, Coach Carter",
  "Our lives are defined by opportunities, even the ones we miss. - Benjamin Button, The Curious Case of Benjamin Button",
  "Our lives are not fully lived if we're not willing to die for those we love, for what we believe. - Martin Luther King Jr. (quoted in Selma)",
  "Sometimes it is the people who no one imagines anything of who do the things that no one can imagine. - Alan Turing, The Imitation Game",
  "We walk away from our dreams afraid we may fail, or worse yet, afraid we may succeed. - Sean Maguire, Good Will Hunting",
  "When a defining moment comes along, you can do one of two things. Define the moment, or let the moment define you. - The Legend of Bagger Vance",
  "Don't ever let somebody tell you you can't do something, not even me. Alright? You dream, you gotta protect it. People can't do something themselves, they wanna tell you you can't do it. If you want something, go get it. Period. - Chris Gardner, The Pursuit of Happyness",
  "Carpe diem. Seize the day, boys. Make your lives extraordinary. - John Keating, Dead Poets Society",
  "It's only after we've lost everything that we're free to do anything. - Tyler Durden, Fight Club",
  "Fear is the mind-killer. - Paul Atreides, Dune",
  "Everything that made that giant tree is already contained inside this tiny little seed. All it needs is some time, a little bit of sunshine and rain, and voila! ... Now, you might not feel like you can do much now, but that's just because, well, you're not a tree yet. You just have to give yourself some time. You're still a seed. - The Lorax",
  "If you focus on what you left behind, you will never be able to see what lies ahead. - Chef Gusteau, Ratatouille",
  "The future is not set. There is no fate but what we make for ourselves. - Sarah Connor, Terminator 2: Judgment Day",
  "Just keep swimming. - Dory, Finding Nemo",
  "With great power comes great responsibility. - Uncle Ben, Spider-Man",
  "I'm not afraid of storms, for I'm learning how to sail my ship. - Amy March, Little Women",
  "After all, tomorrow is another day. - Scarlett O'Hara, Gone With The Wind",
  "You never really understand a person until you consider things from his point of view... until you climb into his skin and walk around in it. - Atticus Finch, To Kill a Mockingbird",
  "The very things that hold you down are going to lift you up. - Timothy Mouse, Dumbo",
  "You is kind. You is smart. You is important. - Aibileen Clark, The Help",
  "To see the world, things dangerous to come to, to see behind walls, to draw closer, to find each other and to feel. That is the purpose of life. - Walter Mitty, The Secret Life of Walter Mitty",
  "How many times do I have to teach you: just because something works doesn't mean it can't be improved. - Shuri, Black Panther",
  "Beginnings are scary, endings are usually sad, but it's the middle that counts the most. - Hope Floats",
  "All I'm saying is, kindness don't have no boundaries. - The Blind Side",
  "You can't change who people are without destroying who they were. - Evan Treborn, The Butterfly Effect",
  "Today is a good day to try. - Quasimodo, The Hunchback of Notre Dame",
  "You can die anytime, but living takes true courage. - Kenshin Himura, Rurouni Kenshin",
  "People's lives don't end when they die, it ends when they lose faith. - Itachi Uchiha, Naruto",
  "If you don't take risks, you can't create a future! - Monkey D. Luffy, One Piece",
  "It's just pathetic to give up on something before you even give it a shot. - Reiko Mikami, Another",
  "There's no shame in falling down! True shame is to not stand up again! - Shintaro Midorima, Kuroko no Basuke",
  "If you can't do something, then don't. Focus on what you can. - Shiro, No Game No Life",
  "Giving up kills people. When people reject giving up… they finally win the right to transcend humanity. - Alucard, Hellsing",
  "You can't sit around envying other people's worlds. You have to go out and change your own. - Light Yagami, Death Note",
  "Knowing what it feels to be in pain, is exactly why we try to be kind to others. - Jiraiya, Naruto",
  "Whatever you lose, you'll find it again. But what you throw away you'll never get back. - Kenshin Himura, Rurouni Kenshin",
  "I too will obtain everything that I desire. Not because someone asked me to do it, but because I know in my heart that I have something worth fighting for. - Vegeta, Dragon Ball Z",
  "Hurt me with the truth. But never comfort me with a lie. - Erza Scarlet, Fairy Tail",
  "I must study lots of things or I won't become a great person. - Nico Robin, One Piece",
  "Reject common sense to make the impossible possible. - Simon, Gurren Lagann",
  "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto Uzumaki, Naruto",
  "I'll leave tomorrow's problems to tomorrow's me. - Spike Spiegel, Cowboy Bebop",
  "A dropout will beat a genius through hard work. - Rock Lee, Naruto",
  "The strong should aid and protect the weak. Then, the weak will become strong, and they in turn will aid and protect those weaker than them. That is the law of nature. - Tanjiro Kamado, Demon Slayer",
  "Nothing's perfect, the world's not perfect, but it's there for us, trying the best it can. That's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
  "When you hit the point of no return, that's the moment it truly becomes a journey. If you can still turn back, it's not really a journey. - Hinata Miyake, A Place Further than the Universe",
  "The difference between a novice and a master is that a master has failed more times than a novice had tried. - Koro-Sensei, Assassination Classroom",
  "No amount of talent trumps hard work. - Rin Matsuoka, Free!",
  "Life is not a game of luck. If you wanna win, work hard. - Sora, No Game No Life",
  "Fear is not evil. It tells you what weakness is. And once you know your weakness, you can become stronger as well as kinder. - Gildarts Clive, Fairy Tail",
  "The ticket to the future is always open. - Vash The Stampede, Trigun",
  "If you don't like the hand that fate's dealt you with, fight for a new one. - Naruto Uzumaki, Naruto",
  "Every journey begins with a single step. We just have to have patience. - Otonashi Yuzuru, Angel Beats!",
  "You've got two legs and a heartbeat. What's stopping you? - Monkey D. Luffy, One Piece",
  "Learn to treasure your life because unfortunately, it can be taken away from you anytime. - L Lawliet, Death Note",
  "It's more important to master the cards you're holding than to complain about the ones your opponent was dealt. - Grimsley, Pokémon",
  "My Motto Is To Be Stronger Than Yesterday. If I Have To, I'll Be Stronger Than Half a Day Ago, Even a Minute Ago! - Rock Lee, Naruto",
  "The Ticket To the Future Is Always Blank. - Vash the Stampede, Trigun",
  "The Moment You Think of Giving Up, Think of the Reason Why You Held on So Long. - Natsu Dragneel, Fairy Tail",
  "You Can't Gain Anything Without Losing Something First. - Edward Elric, Fullmetal Alchemist",
  "To Be Perfect Is To Be Unable To Improve Any Further. - Mayuri Kurotsuchi, Bleach",
  "Remember the Lesson, Not the Disappointment. - Holo the Wise Wolf, Spice & Wolf",
  "Believe in yourself. - Shigeo Kageyama, Mob Psycho 100",
  "In our society, those without power are left behind. - Eren Yeager, Attack on Titan",
  "I want you to be happy. - Kyo Sohma, Fruits Basket",
  "The world isn't perfect. But it's there for us, trying the best it can. That's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
  "We are not defined by our past, but by the choices we make in the present. - Kirito, Sword Art Online",
  "No matter what happens, keep walking on the path you believe in. - Monkey D. Luffy, One Piece",
  "You don't have to be a hero to make a difference. - Izuku Midoriya, My Hero Academia",
  "The heart is what makes us human, even if it sometimes breaks. - Legoshi, Beastars",
  "When you're going through a tough time, just keep going. That's the only way to see the end. - Legoshi, Beastars",
  "Your mistakes don't define you. It's how you rise from them. - Subaru Natsuki, Re:Zero - Starting Life in Another World",
  "Sometimes, the hardest thing to do is nothing. But that's the most powerful thing you can do. - Takemichi Hanagaki, Tokyo Revengers",
  "We may not be able to change the world, but we can change ourselves. - Yuji Itadori, Jujutsu Kaisen",
  "Even the smallest step forward is still progress. - Legoshi, Beastars",
  "Every day is a chance to become the person you want to be. - Izuku Midoriya, My Hero Academia",
  "To truly live, you must live with all of your heart. - Riko, Made in Abyss: Dawn of the Deep Soul",
  "The moment you think you're ready to give up, that's the moment you need to hold on the most. - Takao Akizuki, The Garden of Words",
  "No matter how deep the night, it always turns to day, eventually. - Princess Kaguya, The Tale of the Princess Kaguya",
  "No one can do everything, but everyone can do something. - Hodaka Morishima, Weathering with You",
  "It's not about being perfect, it's about doing your best with what you've been given. - Solomon, Fate/Grand Order: Solomon",
  "All we can do is live until the day we die. Control what we can…and fly free. - Eren Yeager, Attack on Titan",
  "We don't have to know what tomorrow holds! That's why we can live for everything we're worth today! - Natsu Dragneel, Fairy Tail",
  "Life comes at a cost. Wouldn't it be arrogant to die before you've repaid that debt? - Izuku Midoriya, My Hero Academia",
  "Whatever you do, enjoy it to the fullest. That is the secret of life. - Genkai, Yu Yu Hakusho",
  "Simplicity is the easiest path to true beauty. - Juvia Lockser, Fairy Tail",
  "I hate perfection. To be perfect is to be unable to improve any further. - Mayuri Kurotsuchi, Bleach",
  "Even if we forget the faces of our friends, we will never forget the bonds that were carved into our souls. - Otonashi Yuzuru, Angel Beats!",
  "The only way to truly escape the mundane is to lose yourself in the extraordinary. - Lelouch Lamperouge, Code Geass",
  "If you only do what you can do, you'll never be more than you are now. - Master Shifu, Kung Fu Panda",
  "The world isn't perfect. But it's there for us, trying the best it can. That's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
];
